### ISSUE TITLE
Migrate

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/exchange-api#1]
- [x] migrate all issues
- [x] create new repo for npm currency-api (update current readme to point to it)
- [x] check compressed tarball feasibility (7zip gzip) (415 too many files issue, also tried npm-registry-client )
- [x] support only one end point
- [x] make task list
- [x] migrate to npm & pages
- [x] create readme
- [x] warn users with steps to migrate ( in json & readme )
- [ ] push curr-api files with commit history here (check first)
- [ ] other [cdn](https://github.com/fawazahmed0/cdn-open-source/issues/1) (caching issue, max 1 day) and https://github.com/fawazahmed0/exchange-api/issues/42  (possibly esm.sh )

**Comment by Advaith3600** [comment]
> There is no `/currencies/{currencyCode}/{currencyCode}` endpoint in this new API, so please only use `/currencies/{currencyCode}`

Is this endpoint going to be added in the future?

**Comment by omnigenous** [comment]
@fawazahmed0 Could you please keep `YYYY-MM-DD` format?

**Comment by yangshun** [comment]
@fawazahmed0 Thanks for the quick actions in getting the API back up!

Just wanted to report that the new version API (e.g. https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2024.3.1/v1/currencies/usd.json) doesn't seem to work. It'd also be good to continue supporting the old date format `YYYY-MM-DD`, not sure why it has to be changed.

**Comment by omnigenous** [comment]
I was using the API in my bash script :D

I guess I could do `date -u +%Y.%-m.%-d`
