### ISSUE TITLE
cryptos & cleanup (later)

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/exchange-api#43]
add support for all cryptos in currency-api  (need to add all crypto names in json, to avoid issues)
add script in currapi to delete the days folders automatically, everyday, & also clean removing from github repo, using bfg-cleaner
https://rtyley.github.io/bfg-repo-cleaner/

do this before gh marks your account for heavy usage, as they did with opengapps  (see other repo file sizes, to avoid using more space < 5gb)

**Comment by sabatale** [comment]
@fawazahmed0 Any way to remove crypto through URL query?

e.g., https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.json?crypto=false
