### ISSUE TITLE
Gold Gram Support

### ISSUE THREAD

**Issue by ahmeterenodaci** [fawazahmed0/exchange-api#47]
Is it possible to add [gold gram](https://www.investing.com/currencies/gau-usd) to currency-api?

**Comment by mohamed-mosaad-bakr** [comment]
In the exchange rate feature, is it possible to add a custom currency and change the base currency from USD? For example, changing the base currency from USD to XAU and creating a new currency named "Gold Gram" which is equivalent to 0.0321507 XAU.

![Image](https://github.com/user-attachments/assets/c7ae538f-022a-4149-a675-75664b4931ee)
